package recipes

// OpenCode and OpenClaw both load plugins from a per-user directory
// where each plugin is a TypeScript (transpiled to JS) file with a
// predictable shape. We ship a tiny pre-compiled JS shim that spawns
// `oryxai hook --agent <name>` as a child process and pipes the
// agent's tool-call envelope.
//
// Honest caveat: without re-checking the agent's plugin ABI on every
// release, this integration may break if upstream changes the
// signature. We mark it ModeHook anyway because when it works it's
// real enforcement.

import (
	"fmt"
	"os"
	"path/filepath"
)

// opencodePluginJS is the literal JS plugin body. Kept as a Go string
// constant so the plugin ships embedded in the binary — no separate
// asset to lose.
const opencodePluginJS = `// oryxai plugin for OpenCode — auto-generated by 'oryxai install'.
// On every tool execution, spawns 'oryxai hook --agent opencode' and
// pipes the tool envelope. Hook returns allow within ~5 ms; we never
// block tool execution waiting on it.
//
// Marker so 'oryxai uninstall' can find + remove this file:
// __oryxai_managed__

import { spawn } from "node:child_process";

export default {
  name: "oryxai",
  version: "0.1.0",
  async beforeTool(ctx) {
    const child = spawn("ORYXAI_HOOK_PATH", ["hook", "--agent", "opencode"], {
      stdio: ["pipe", "pipe", "pipe"],
    });
    child.stdin.write(JSON.stringify(ctx));
    child.stdin.end();
    // Non-blocking — let the agent proceed regardless of hook outcome.
    return { decision: "allow" };
  },
};
`

const openclawPluginJS = `// oryxai plugin for OpenClaw — auto-generated by 'oryxai install'.
// __oryxai_managed__

import { spawn } from "node:child_process";

export default {
  name: "oryxai",
  version: "0.1.0",
  before_tool_call: async (ctx) => {
    const child = spawn("ORYXAI_HOOK_PATH", ["hook", "--agent", "openclaw"], {
      stdio: ["pipe", "pipe", "pipe"],
    });
    child.stdin.write(JSON.stringify(ctx));
    child.stdin.end();
    return { decision: "allow" };
  },
};
`

// ─── OpenCode ────────────────────────────────────────────────────

type OpenCodeRecipe struct{}

func (OpenCodeRecipe) Name() string        { return "opencode" }
func (OpenCodeRecipe) DisplayName() string { return "OpenCode" }
func (OpenCodeRecipe) Mode() Mode          { return ModeHook }
func (OpenCodeRecipe) Detect() error {
	p, _ := HomePath(".opencode")
	if FileExists(p) {
		return nil
	}
	return ErrNotInstalled
}
func (OpenCodeRecipe) Install(ctx InstallContext) error {
	dir, err := HomePath(".opencode", "plugins", "oryxai")
	if err != nil {
		return err
	}
	if ctx.DryRun {
		fmt.Printf("--- would install %s/index.js (OpenCode plugin) ---\n", dir)
		return nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	// Substitute the binary path so spawn() finds it.
	body := replaceAll(opencodePluginJS, "ORYXAI_HOOK_PATH", ctx.HookPath)
	return AtomicWriteFile(filepath.Join(dir, "index.js"), []byte(body), 0o644)
}
func (OpenCodeRecipe) Uninstall() error {
	dir, err := HomePath(".opencode", "plugins", "oryxai")
	if err != nil {
		return err
	}
	if !FileExists(dir) {
		return nil
	}
	return os.RemoveAll(dir)
}

// ─── OpenClaw ───────────────────────────────────────────────────

type OpenClawRecipe struct{}

func (OpenClawRecipe) Name() string        { return "openclaw" }
func (OpenClawRecipe) DisplayName() string { return "OpenClaw" }
func (OpenClawRecipe) Mode() Mode          { return ModeHook }
func (OpenClawRecipe) Detect() error {
	p, _ := HomePath(".openclaw")
	if FileExists(p) {
		return nil
	}
	return ErrNotInstalled
}
func (OpenClawRecipe) Install(ctx InstallContext) error {
	dir, err := HomePath(".openclaw", "plugins", "oryxai")
	if err != nil {
		return err
	}
	if ctx.DryRun {
		fmt.Printf("--- would install %s/index.js (OpenClaw plugin) ---\n", dir)
		return nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	body := replaceAll(openclawPluginJS, "ORYXAI_HOOK_PATH", ctx.HookPath)
	return AtomicWriteFile(filepath.Join(dir, "index.js"), []byte(body), 0o644)
}
func (OpenClawRecipe) Uninstall() error {
	dir, err := HomePath(".openclaw", "plugins", "oryxai")
	if err != nil {
		return err
	}
	if !FileExists(dir) {
		return nil
	}
	return os.RemoveAll(dir)
}

// replaceAll is a tiny local helper (we deliberately avoid importing
// strings.ReplaceAll here to keep this file dep-free). Trivial cost.
func replaceAll(s, old, new string) string {
	for {
		i := indexOf(s, old)
		if i < 0 {
			return s
		}
		s = s[:i] + new + s[i+len(old):]
	}
}

func indexOf(s, sub string) int {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return i
		}
	}
	return -1
}
